import { Coin } from "./coin.js"
import { Player } from "./player.js"
import { Enemy } from "./enemy.js"
import { BoxCoin, BoxMushroom, BoxStar, BoxExtraLife, BreakableBlock} from "./box.js"

export const levelChars = {
	".": "empty",
	",": "sprint-block",
	"m": "enemy-block-block",
	"+": "ground-top-left",
	"#": "ground-top-body",
	"|": "ground-top-right",
	V: "ground-bottom-left",
	"=": "ground-bottom-body",
	"%": "ground-bottom-right",
	x: "ground-full",
	g: "ground-dead",
	"[": "top-left-cloud",
	Q: "top-middle-cloud",
	"]": "top-right-cloud",
	"{": "bottom-left-cloud",
	q: "bottom-middle-cloud",
	"}": "bottom-right-cloud",
	H: "block",
	B: BreakableBlock,
	C: BoxCoin,
	//	ק: BoxEmpty,
	"&": BoxMushroom,
	"*": BoxStar,
	X: BoxExtraLife,
	w: "basic-bush",
	1: "pipe-top-left",
	2: "pipe-top-right",
	3: "pipe-body-left",
	4: "pipe-body-right",
	I: "mountain-main-top-left",
	R: "mountain-main-top-right",
	i: "mountain-main-body-left",
	r: "mountain-main-body-right",
	A: "mountain-child-a-left",
	Z: "mountain-child-a-right",
	a: "mountain-child-b-left",
	z: "mountain-child-b-right",
	U: "castle-body",
	K: "castle-door-top",
	k: "castle-door-bottom",
	D: "flag1",
	F: "flag2",
	d: "flag3",
	f: "flag4",
	"!": "pole1",
	"£": "pole2",
	"@": Player,
	o: Coin,
	E: Enemy,
}
